name: Continuous Integration

on:
  push:
    branches: 
      - main
      - develop
  pull_request:
    branches: 
      - main
      - develop
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  terraform-security:
    name: Terraform Security Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy for Terraform
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: 'aws/terraform'
          format: 'sarif'
          output: 'trivy-terraform-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
          exit-code: '0'

      - name: Upload Trivy Terraform scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-terraform-results.sarif'
          category: 'terraform-security'

      - name: Run Trivy for Terraform with table format
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: 'aws/terraform'
          format: table
          severity: 'CRITICAL,HIGH,MEDIUM'
          exit-code: '1'

      - name: Upload Trivy results as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: trivy-terraform-results
          path: trivy-terraform-results.sarif
          retention-days: 30
